"""Generate the site's raster image assets from the brand tokens.

Run from the repository root:

    python tools/make-assets.py

Writes favicon.ico, apple-touch-icon.png and og-image.png. The vector mark is
generated by make-mark.py and is not touched here; these are the raster
fallbacks that older browsers and every social platform still require.

The blade geometry is imported from make-mark.py rather than redrawn, so the
PNG and the SVG cannot drift apart. Regenerate whenever the mark or the brand
colours change, and commit the output. The files are small enough that keeping
them in the repository is simpler than adding a build step to a site that
otherwise has none.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

# Brand tokens, matching the :root block in index.html. Under the brand brief
# charcoal is typography only, so it is the ink here and never a ground.
INK = (30, 35, 39)            # --ink, charcoal: type
INK_2 = (82, 88, 92)
SLATE = (138, 144, 152)       # --ink-3, slate: accent
PAPER = (251, 250, 247)       # --paper, warm white: the ground
SANDSTONE = (236, 231, 219)   # --paper-3, sandstone: secondary
COPPER = (183, 83, 46)        # --redline, oxidised copper: primary
COPPER_GOLD = (209, 138, 77)  # --copper
RULE = (227, 222, 210)        # --rule

# The mark's geometry lives in make-mark.py so the vector and the raster
# cannot drift apart. Importing by path because the filename has a hyphen.
import importlib.util as _ilu
_spec = _ilu.spec_from_file_location(
    "_mark", str(Path(__file__).resolve().parent / "make-mark.py"))
_mark_mod = _ilu.module_from_spec(_spec)
_spec.loader.exec_module(_mark_mod)

ROOT = Path(__file__).resolve().parent.parent / "public"

FRAME = 64.0  # the mark's own coordinate frame, from make-mark.py

#: Tried in order. Arial is on every Windows machine; the rest cover macOS and
#: Linux so the script is not silently Windows-only.
FONT_CANDIDATES = {
    "bold": [
        "C:/Windows/Fonts/arialbd.ttf",
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    ],
    "regular": [
        "C:/Windows/Fonts/arial.ttf",
        "/System/Library/Fonts/Supplemental/Arial.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ],
    "mono": [
        "C:/Windows/Fonts/consola.ttf",
        "/System/Library/Fonts/Menlo.ttc",
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    ],
}


def load(weight: str, size: int) -> ImageFont.FreeTypeFont:
    for path in FONT_CANDIDATES[weight]:
        if Path(path).exists():
            return ImageFont.truetype(path, size)
    raise SystemExit(
        f"No {weight} font found. Add a path for this machine to "
        "FONT_CANDIDATES in tools/make-assets.py."
    )


def tracked(draw: ImageDraw.ImageDraw, xy, text: str, font, fill,
            spacing: float = 0.0) -> float:
    """Draw text with manual letter-spacing, which Pillow does not support."""
    x, y = xy
    for char in text:
        draw.text((x, y), char, font=font, fill=fill)
        x += draw.textlength(char, font=font) + spacing
    return x


def draw_mark(draw: ImageDraw.ImageDraw, x: float, y: float, size: float,
              fill=COPPER, second=None, stop=None, gap=2.4) -> None:
    """Paint the aperture with its top-left at (x, y), `size` units square."""
    kwargs = {"gap": gap}
    if stop is not None:
        kwargs["stop"] = stop
    scale = size / FRAME
    for k, blade in enumerate(_mark_mod.shapes(**kwargs)):
        colour = second if (second is not None and k % 2) else fill
        draw.polygon(_mark_mod.scaled(blade, scale, x, y), fill=colour)


def make_icon(size: int, pad_ratio: float = 0.06, ground=None) -> Image.Image:
    """The aperture in copper on warm white.

    Supersampled four times and reduced, because Pillow will not antialias a
    polygon on its own and a hard blade edge at 32 pixels looks like a
    mistake. The blades are opened wider and the gaps cut deeper than the
    display mark: at 16 pixels the display separations close up and leave a
    solid copper hexagon, which is the one failure mode worth designing out.
    """
    ss = 4
    big = size * ss
    ground = tuple(ground) + (255,) if ground else (0, 0, 0, 0)
    image = Image.new("RGBA", (big, big), ground)
    draw = ImageDraw.Draw(image)

    inset = big * pad_ratio
    draw_mark(draw, inset, inset, big - inset * 2,
              fill=COPPER + (255,), stop=0.84, gap=3.2)
    return image.resize((size, size), Image.LANCZOS)


def write_favicon() -> None:
    sizes = [16, 32, 48, 64]
    base = make_icon(256)
    base.save(ROOT / "favicon.ico", format="ICO",
              sizes=[(s, s) for s in sizes])
    print("favicon.ico", sizes)


def write_apple_touch() -> None:
    # Apple composites onto white if the icon is transparent, and does not
    # round the corners itself on modern iOS, so ship it opaque and square.
    icon = make_icon(180, pad_ratio=0.19, ground=PAPER).convert("RGB")
    icon.save(ROOT / "apple-touch-icon.png", format="PNG")
    print("apple-touch-icon.png 180x180")


def write_og_image() -> None:
    """The share card: warm white, one copper mark, charcoal type.

    Drawn at twice size and reduced, so the aperture's diagonals are clean.
    """
    ss = 2
    width, height = 1200, 630
    image = Image.new("RGB", (width * ss, height * ss), PAPER)
    draw = ImageDraw.Draw(image)

    left = 88 * ss
    draw_mark(draw, left, 116 * ss, 96 * ss, fill=COPPER)

    name = load("bold", 84 * ss)
    label = load("mono", 24 * ss)
    line = load("regular", 33 * ss)

    # Wide-tracked caps, matching the lockup on the site rather than the
    # tight setting the card used to carry.
    tracked(draw, (left, 258 * ss), "GOSSANS", name, INK, spacing=17 * ss)
    tracked(draw, (left + 2 * ss, 372 * ss), "EARTH INTELLIGENCE",
            label, COPPER_GOLD, spacing=5 * ss)

    draw.line([(left, 444 * ss), ((width - 88) * ss, 444 * ss)],
              fill=RULE, width=2 * ss)

    tracked(draw, (left, 476 * ss),
            "PRODUCTION OUTLOOK SIMULATION & OPPORTUNITY SCREENING",
            label, COPPER, spacing=2.4 * ss)

    draw.text((left, 528 * ss),
              "Your production data already holds the answer.",
              font=line, fill=INK_2)

    # A copper rule along the foot, so the card reads even as a thumbnail.
    draw.rectangle([0, (height - 9) * ss, width * ss, height * ss],
                   fill=COPPER)

    image = image.resize((width, height), Image.LANCZOS)
    image.save(ROOT / "og-image.png", format="PNG", optimize=True)
    print("og-image.png %dx%d" % (width, height))


def write_proof() -> None:
    """Every size that matters, on one sheet, so the gaps can be checked.

    The specific risk with an aperture is that the blade separations fall
    below a pixel and the mark collapses into a solid hexagon. This makes that
    visible rather than assumed.
    """
    sizes = [16, 20, 24, 32, 48, 64, 96, 128]
    pad, gap = 24, 20
    w = pad * 2 + sum(sizes) + gap * (len(sizes) - 1)
    h = pad * 2 + max(sizes)
    sheet = Image.new("RGB", (w, h), PAPER)
    x = pad
    for s in sizes:
        cell = make_icon(s)
        sheet.paste(cell, (x, pad + (max(sizes) - s) // 2), cell)
        x += s + gap
    out = Path(__file__).resolve().parent.parent / "mark-proof.png"
    sheet.save(out, format="PNG")
    print("mark-proof.png", sizes, "->", out)


if __name__ == "__main__":
    write_favicon()
    write_apple_touch()
    write_og_image()
    write_proof()
    print("\nDone. Commit the generated files. mark-proof.png is a check, "
          "not an asset.")
